[Variables]
Dv.Sy_11.Ui=%HOMEDRIVE%\Users\[mUserName]\AppData\Local\Microsoft\Windows\AccountPicture\UserImage.jpg
Dv.Sy_10.Ui=%HOMEDRIVE%\Users\[mUserName]\AppData\Roaming\Microsoft\Windows\AccountPicture\UserImage.jpg
Dv.Sy_8.Ui=%HOMEDRIVE%\Users\[mUserName]\AppData\Local\Temp\[mUserName].bmp
Dv.Sy_7.Ui=%HOMEDRIVE%\Users\[mUserName]\AppData\Local\Temp\[mUserName].bmp

Dv.Sy_11.Bl.BG.Md=2
Dv.Sy_10.Bl.BG.Md=2
Dv.Sy_8.Bl.BG.Md=0
Dv.Sy_7.Bl.BG.Md=1

Dv.Sy_11.Bl.BG.Ty=2
Dv.Sy_10.Bl.BG.Ty=2
Dv.Sy_8.Bl.BG.Ty=0
Dv.Sy_7.Bl.BG.Ty=1

Dv.Sy_11.Bl.BG.Bd=2
Dv.Sy_10.Bl.BG.Bd=2
Dv.Sy_8.Bl.BG.Bd=0
Dv.Sy_7.Bl.BG.Bd=1