[Variables]
HdBkBt=0
BkBtAc=[!WriteKeyValue "Variables" "Page" "04" "#Pk@#Config\SkinSettings\#Sk.Nm#.inc"][!Refresh]
QtBtAc=[]
CfBtAc_0=[]
CfBtAc_1=[]

HdNtBt=0
NtBtTx=#Tm.Next#
NtBtAc=[!WriteKeyValue "Variables" "Page" "06" "#Pk@#Config\SkinSettings\#Sk.Nm#.inc"][!Refresh]

|Mt.Text.01|.LUMA=["https://github.com/SteveHsuDrawing/quantoflx/wiki/Manual-of-%22Quanto-Flx-System%22-Package#before-you-use-them"]
|Mt.Text.01|.MAC=1
|Mt.Text.01|.MACN=HAND