[Variables]
Dv.Sy_11.Ui=%HOMEDRIVE%\Users\%USERNAME%\AppData\Local\Microsoft\Windows\AccountPicture\UserImage.jpg
Dv.Sy_10.Ui=%HOMEDRIVE%\Users\%USERNAME%\AppData\Roaming\Microsoft\Windows\AccountPicture\UserImage.jpg
Dv.Sy_8.Ui=%HOMEDRIVE%\Users\%USERNAME%\AppData\Local\Temp\%USERNAME%.bmp
Dv.Sy_7.Ui=%HOMEDRIVE%\Users\%USERNAME%\AppData\Local\Temp\%USERNAME%.bmp

Dv.Sy_11.Bl.Bg.Md=2
Dv.Sy_10.Bl.Bg.Md=2
Dv.Sy_8.Bl.Bg.Md=0
Dv.Sy_7.Bl.Bg.Md=1

Dv.Sy_11.Bl.Bg.Ty=1
Dv.Sy_10.Bl.Bg.Ty=1
Dv.Sy_8.Bl.Bg.Ty=0
Dv.Sy_7.Bl.Bg.Ty=0

Dv.Sy_11.Bl.Bg.Bd=1
Dv.Sy_10.Bl.Bg.Bd=1
Dv.Sy_8.Bl.Bg.Bd=0
Dv.Sy_7.Bl.Bg.Bd=0

Dv.Sy_11.Bl.Bg.Cn=1
Dv.Sy_10.Bl.Bg.Cn=0
Dv.Sy_8.Bl.Bg.Cn=0
Dv.Sy_7.Bl.Bg.Cn=0

Dv.Sy_11.FlCs.UNS=1
Dv.Sy_10.FlCs.UNS=1
Dv.Sy_8.FlCs.UNS=0
Dv.Sy_7.FlCs.UNS=0