[Variables]
CmLs.Weather\Daily.CMCommon.T01=#Tm.Skin_Settings#
CmLs.Weather\Daily.CMCommon.T02=#Tm.Manage_Project#
CmLs.Weather\Daily.CMCommon.T03=-
CmLs.Weather\Daily.CMCommon.T04=#Tm.Help#
CmLs.Weather\Daily.CMCommon.T05=-
CmLs.Weather\Daily.CMCommon.T06=#Tm.Variants#
CmLs.Weather\Daily.CMCommon.T07=#Tm.Refresh#
CmLs.Weather\Daily.CMCommon.T08=#Tm.Unload#
CmLs.Weather\Daily.CMCommon.T09=#Tm.More#
CmLs.Weather\Daily.CMCommon.T10=

CmLs.Weather\Daily.CMCommon.A01=#Ac.Skin_Settings#
CmLs.Weather\Daily.CMCommon.A02=#Ac.Manage_Project#
CmLs.Weather\Daily.CMCommon.A03=[]
CmLs.Weather\Daily.CMCommon.A04=["https://github.com/SteveHsuDrawing/quantoflx/wiki/Manual-of-%22Quanto-Flx-Gadgets%22-Package#Weather"]
CmLs.Weather\Daily.CMCommon.A05=[]
CmLs.Weather\Daily.CMCommon.A06=#Ac.Variants#
CmLs.Weather\Daily.CMCommon.A07=#Ac.Refresh#
CmLs.Weather\Daily.CMCommon.A08=#Ac.Unload#
CmLs.Weather\Daily.CMCommon.A09=#Ac.More#
CmLs.Weather\Daily.CMCommon.A10=[]

CmLs.Weather\Daily.CMStyle.T01=2x2
CmLs.Weather\Daily.CMStyle.T02=4x1
CmLs.Weather\Daily.CMStyle.T03=4x2 A
CmLs.Weather\Daily.CMStyle.T04=4x2 B
CmLs.Weather\Daily.CMStyle.T05=4x4 A
CmLs.Weather\Daily.CMStyle.T06=4x4 B
CmLs.Weather\Daily.CMStyle.T07=8x4 (Temperature)
CmLs.Weather\Daily.CMStyle.T08=8x4 (Apparent Temperature)
CmLs.Weather\Daily.CMStyle.T09=8x4 (UV Index)
CmLs.Weather\Daily.CMStyle.T10=8x4 (Precipitation)
CmLs.Weather\Daily.CMStyle.T11=8x4 (Precipitation Probability)
CmLs.Weather\Daily.CMStyle.T12=8x4 (Wind Speed)
CmLs.Weather\Daily.CMStyle.T13=

CmLs.Weather\Daily.CMStyle.A01=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Daily" "2x2.ini"]
CmLs.Weather\Daily.CMStyle.A02=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Daily" "4x1.ini"]
CmLs.Weather\Daily.CMStyle.A03=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Daily" "4x2_A.ini"]
CmLs.Weather\Daily.CMStyle.A04=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Daily" "4x2_B.ini"]
CmLs.Weather\Daily.CMStyle.A05=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Daily" "4x4_A.ini"]
CmLs.Weather\Daily.CMStyle.A06=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Daily" "4x4_B.ini"]
CmLs.Weather\Daily.CMStyle.A07=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Daily" "8x4_Temperature.ini"]
CmLs.Weather\Daily.CMStyle.A08=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Daily" "8x4_ApparentTemperature.ini"]
CmLs.Weather\Daily.CMStyle.A09=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Daily" "8x4_UVIndex.ini"]
CmLs.Weather\Daily.CMStyle.A10=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Daily" "8x4_Precipitation.ini"]
CmLs.Weather\Daily.CMStyle.A11=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Daily" "8x4_PrecipitationProbability.ini"]
CmLs.Weather\Daily.CMStyle.A12=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Daily" "8x4_Wind.ini"]
CmLs.Weather\Daily.CMStyle.A13=

CmLs.Weather\Daily.CMChooseDisplayParameter.T01=#Tm.Temperature#
CmLs.Weather\Daily.CMChooseDisplayParameter.T02=#Tm.Apparent_Temperature#
CmLs.Weather\Daily.CMChooseDisplayParameter.T03=#Tm.UV_Index#
CmLs.Weather\Daily.CMChooseDisplayParameter.T04=#Tm.Precipitation#
CmLs.Weather\Daily.CMChooseDisplayParameter.T05=#Tm.Precipitation_Probability#
CmLs.Weather\Daily.CMChooseDisplayParameter.T06=#Tm.Wind#
CmLs.Weather\Daily.CMChooseDisplayParameter.T07=

CmLs.Weather\Daily.CMChooseDisplayParameter.A01=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Daily" "8x4_Temperature.ini"]
CmLs.Weather\Daily.CMChooseDisplayParameter.A02=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Daily" "8x4_ApparentTemperature.ini"]
CmLs.Weather\Daily.CMChooseDisplayParameter.A03=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Daily" "8x4_UVIndex.ini"]
CmLs.Weather\Daily.CMChooseDisplayParameter.A04=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Daily" "8x4_Precipitation.ini"]
CmLs.Weather\Daily.CMChooseDisplayParameter.A05=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Daily" "8x4_PrecipitationProbability.ini"]
CmLs.Weather\Daily.CMChooseDisplayParameter.A06=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Daily" "8x4_Wind.ini"]
CmLs.Weather\Daily.CMChooseDisplayParameter.A07=
