[Variables]
CmLs.Weather\Hourly.CMCommon.T01=#Tm.Skin_Settings#
CmLs.Weather\Hourly.CMCommon.T02=#Tm.Manage_Project#
CmLs.Weather\Hourly.CMCommon.T03=-
CmLs.Weather\Hourly.CMCommon.T04=#Tm.Help#
CmLs.Weather\Hourly.CMCommon.T05=-
CmLs.Weather\Hourly.CMCommon.T06=#Tm.Variants#
CmLs.Weather\Hourly.CMCommon.T07=#Tm.Refresh#
CmLs.Weather\Hourly.CMCommon.T08=#Tm.Unload#
CmLs.Weather\Hourly.CMCommon.T09=#Tm.More#
CmLs.Weather\Hourly.CMCommon.T10=

CmLs.Weather\Hourly.CMCommon.A01=#Ac.Skin_Settings#
CmLs.Weather\Hourly.CMCommon.A02=#Ac.Manage_Project#
CmLs.Weather\Hourly.CMCommon.A03=[]
CmLs.Weather\Hourly.CMCommon.A04=["https://github.com/SteveHsuDrawing/quantoflx/wiki/Manual-of-%22Quanto-Flx-Gadgets%22-Package#Weather"]
CmLs.Weather\Hourly.CMCommon.A05=[]
CmLs.Weather\Hourly.CMCommon.A06=#Ac.Variants#
CmLs.Weather\Hourly.CMCommon.A07=#Ac.Refresh#
CmLs.Weather\Hourly.CMCommon.A08=#Ac.Unload#
CmLs.Weather\Hourly.CMCommon.A09=#Ac.More#
CmLs.Weather\Hourly.CMCommon.A10=[]

CmLs.Weather\Hourly.CMStyle.T01=2x2
CmLs.Weather\Hourly.CMStyle.T02=4x1
CmLs.Weather\Hourly.CMStyle.T03=4x2 A
CmLs.Weather\Hourly.CMStyle.T04=4x2 B
CmLs.Weather\Hourly.CMStyle.T05=4x4 A
CmLs.Weather\Hourly.CMStyle.T06=4x4 B
CmLs.Weather\Hourly.CMStyle.T07=8x4 (Temperature)
CmLs.Weather\Hourly.CMStyle.T08=8x4 (Apparent Temperature)
CmLs.Weather\Hourly.CMStyle.T09=8x4 (Dew Point)
CmLs.Weather\Hourly.CMStyle.T10=8x4 (Humidity)
CmLs.Weather\Hourly.CMStyle.T11=8x4 (Precipitation Probability)
CmLs.Weather\Hourly.CMStyle.T12=8x4 (Precipitation)
CmLs.Weather\Hourly.CMStyle.T13=8x4 (Surface Pressure)
CmLs.Weather\Hourly.CMStyle.T14=8x4 (Cloud Cover)
CmLs.Weather\Hourly.CMStyle.T15=8x4 (Visibility)
CmLs.Weather\Hourly.CMStyle.T16=8x4 (Wind)
CmLs.Weather\Hourly.CMStyle.T17=8x4 (UV Index)
CmLs.Weather\Hourly.CMStyle.T18=

CmLs.Weather\Hourly.CMStyle.A01=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Hourly" "2x2.ini"]
CmLs.Weather\Hourly.CMStyle.A02=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Hourly" "4x1.ini"]
CmLs.Weather\Hourly.CMStyle.A03=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Hourly" "4x2_A.ini"]
CmLs.Weather\Hourly.CMStyle.A04=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Hourly" "4x2_B.ini"]
CmLs.Weather\Hourly.CMStyle.A05=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Hourly" "4x4_A.ini"]
CmLs.Weather\Hourly.CMStyle.A06=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Hourly" "4x4_B.ini"]
CmLs.Weather\Hourly.CMStyle.A07=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Hourly" "8x4_Temperature.ini]
CmLs.Weather\Hourly.CMStyle.A08=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Hourly" "8x4_ApparentTemperature.ini]
CmLs.Weather\Hourly.CMStyle.A09=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Hourly" "8x4_DewPoint.ini]
CmLs.Weather\Hourly.CMStyle.A10=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Hourly" "8x4_Humidity.ini]
CmLs.Weather\Hourly.CMStyle.A11=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Hourly" "8x4_PrecipitationProbability.ini]
CmLs.Weather\Hourly.CMStyle.A12=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Hourly" "8x4_Precipitation.ini]
CmLs.Weather\Hourly.CMStyle.A13=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Hourly" "8x4_SurfacePressure.ini]
CmLs.Weather\Hourly.CMStyle.A14=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Hourly" "8x4_CloudCover.ini]
CmLs.Weather\Hourly.CMStyle.A15=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Hourly" "8x4_Visibility.ini]
CmLs.Weather\Hourly.CMStyle.A16=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Hourly" "8x4_Wind.ini]
CmLs.Weather\Hourly.CMStyle.A17=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Hourly" "8x4_UVIndex.ini]
CmLs.Weather\Hourly.CMStyle.A18=

CmLs.Weather\Hourly.CMChooseDisplayParameter.T01=#Tm.Temperature#
CmLs.Weather\Hourly.CMChooseDisplayParameter.T02=#Tm.Apparent_Temperature#
CmLs.Weather\Hourly.CMChooseDisplayParameter.T03=#Tm.Dew_Point#
CmLs.Weather\Hourly.CMChooseDisplayParameter.T04=#Tm.Humidity#
CmLs.Weather\Hourly.CMChooseDisplayParameter.T05=#Tm.Precipitation_Probability#
CmLs.Weather\Hourly.CMChooseDisplayParameter.T06=#Tm.Precipitation#
CmLs.Weather\Hourly.CMChooseDisplayParameter.T07=#Tm.Surface_Pressure#
CmLs.Weather\Hourly.CMChooseDisplayParameter.T08=#Tm.Cloud_Cover#
CmLs.Weather\Hourly.CMChooseDisplayParameter.T09=#Tm.Visibility#
CmLs.Weather\Hourly.CMChooseDisplayParameter.T10=#Tm.Wind#
CmLs.Weather\Hourly.CMChooseDisplayParameter.T11=#Tm.UV_Index#
CmLs.Weather\Hourly.CMChooseDisplayParameter.T12=

CmLs.Weather\Hourly.CMChooseDisplayParameter.A01=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Hourly" "8x4_Temperature.ini]
CmLs.Weather\Hourly.CMChooseDisplayParameter.A02=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Hourly" "8x4_ApparentTemperature.ini]
CmLs.Weather\Hourly.CMChooseDisplayParameter.A03=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Hourly" "8x4_DewPoint.ini]
CmLs.Weather\Hourly.CMChooseDisplayParameter.A04=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Hourly" "8x4_Humidity.ini]
CmLs.Weather\Hourly.CMChooseDisplayParameter.A05=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Hourly" "8x4_PrecipitationProbability.ini]
CmLs.Weather\Hourly.CMChooseDisplayParameter.A06=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Hourly" "8x4_Precipitation.ini]
CmLs.Weather\Hourly.CMChooseDisplayParameter.A07=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Hourly" "8x4_SurfacePressure.ini]
CmLs.Weather\Hourly.CMChooseDisplayParameter.A08=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Hourly" "8x4_CloudCover.ini]
CmLs.Weather\Hourly.CMChooseDisplayParameter.A09=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Hourly" "8x4_Visibility.ini]
CmLs.Weather\Hourly.CMChooseDisplayParameter.A10=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Hourly" "8x4_Wind.ini]
CmLs.Weather\Hourly.CMChooseDisplayParameter.A11=[!ActivateConfig "#ROOTCONFIG#\Package\QuantoFlx.Gadgets\Weather\Hourly" "8x4_UVIndex.ini]
CmLs.Weather\Hourly.CMChooseDisplayParameter.A12=











